import { Search, X, ChevronLeft, ChevronRight, Inbox, AlertCircle } from 'lucide-react';
import { useEffect } from 'react';
export function StatusBadge({ status }) { return <span className={`status-badge status-${String(status).toLowerCase().replace(/\s/g, '-')}`}>{status}</span>; }
export function PageHeader({ eyebrow = 'ADMINISTRATION', title, text, action }) { return <header className="admin-page-header"><div><p>{eyebrow}</p><h1>{title}</h1>{text && <span>{text}</span>}</div>{action}</header>; }
export function SearchBox({ value, onChange, placeholder = 'Search...' }) { return <label className="admin-search"><Search size={17}/><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder}/>{value && <button type="button" aria-label="Clear search" onClick={() => onChange('')}><X size={15}/></button>}</label>; }
export function EmptyState({ title = 'Nothing to display.', text }) { return <div className="admin-empty"><Inbox size={28}/><h3>{title}</h3>{text && <p>{text}</p>}</div>; }
export function ErrorState({ onRetry }) { return <div className="admin-empty"><AlertCircle size={28}/><h3>We could not load this page.</h3><button className="admin-btn secondary" onClick={onRetry}>Try again</button></div>; }
export function LoadingState() { return <div className="admin-loading"><i/><i/><i/></div>; }
export function Pagination({ page, total, onPage }) { if (total <= 1) return null; return <nav className="pagination" aria-label="Pagination"><button disabled={page === 1} onClick={() => onPage(page - 1)}><ChevronLeft size={16}/> Previous</button>{Array.from({ length: total }, (_, i) => <button key={i} className={page === i + 1 ? 'current' : ''} onClick={() => onPage(i + 1)}>{i + 1}</button>)}<button disabled={page === total} onClick={() => onPage(page + 1)}>Next <ChevronRight size={16}/></button></nav>; }
export function ConfirmDialog({ dialog, onClose, onConfirm }) { useEffect(() => { const close = (e) => e.key === 'Escape' && onClose(); addEventListener('keydown', close); return () => removeEventListener('keydown', close); }, [onClose]); if (!dialog) return null; return <div className="admin-modal-backdrop" onMouseDown={onClose}><section className="admin-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title" onMouseDown={(e) => e.stopPropagation()}><p>PLEASE CONFIRM</p><h2 id="confirm-title">{dialog.title}</h2><span>{dialog.text}</span><div><button className="admin-btn secondary" onClick={onClose}>Cancel</button><button className="admin-btn danger" onClick={onConfirm}>{dialog.confirm || 'Delete'}</button></div></section></div>; }
export function Toast({ message, onDismiss }) { useEffect(() => { if (!message) return; const timer = setTimeout(onDismiss, 3200); return () => clearTimeout(timer); }, [message, onDismiss]); return message ? <div className="admin-toast" role="status">{message}<button onClick={onDismiss} aria-label="Dismiss notification"><X size={16}/></button></div> : null; }
