import { useEffect, useMemo, useState } from 'react';
import Header from '../components/Header'; import Hero from '../components/Hero'; import FeaturedPost from '../components/FeaturedPost'; import ContentCard from '../components/ContentCard'; import VideoSection from '../components/VideoSection'; import Chatbot from '../components/Chatbot'; import Footer from '../components/Footer'; import EditorialGallery from '../components/EditorialGallery'; import { TopicAccordion, ReaderNotes } from '../components/EditorialExtras'; import AuthModal from '../components/AuthModal';
import { getBlogs, getFeaturedContent, getTopics, getVideos, googleAuthUrl } from '../services/contentApi'; import { Play, X } from 'lucide-react';

export default function HomePage({ onAuthenticate }) {
  const blogData = null; const videoData = null;
  const [query, setQuery] = useState(''); const [video, setVideo] = useState(null); const [authMode, setAuthMode] = useState(null); const [remoteContent, setRemoteContent] = useState({ blogs: [], videos: [], featured: null, topics: [], loading: true, error: '' });
  useEffect(() => { if (blogData || videoData) return; const controller = new AbortController(); Promise.all([getBlogs(controller.signal), getVideos(controller.signal)]).then(([blogs, remoteVideos]) => setRemoteContent({ blogs, videos: remoteVideos, loading: false, error: '' })).catch((error) => { if (error.name !== 'AbortError') setRemoteContent((current) => ({ ...current, loading: false, error: 'Không thể tải dữ liệu mới. Đang hiển thị nội dung tạm thời.' })); }); return () => controller.abort(); }, [blogData, videoData]);
  const blogItems = remoteContent.blogs; const videoItems = remoteContent.videos;
  const filtered = useMemo(() => blogItems.filter((p) => `${p.title} ${p.type} ${p.description}`.toLowerCase().includes(query.toLowerCase())), [blogItems, query]); const authenticate = (form, mode) => form ? onAuthenticate?.(form, mode) : setAuthMode(mode);
  return <><Header onSearch={setQuery} onAuth={setAuthMode}/><main className="site-main"><Hero onSearch={setQuery}/><FeaturedPost/><section className="section latest" id="community"><div className="section-heading"><div><p>THE LATEST</p><h2>Fresh, useful ideas for the way you really eat.</h2></div><a href="#community">View all</a></div>{remoteContent.loading && <p className="content-status">Đang tải blog từ hệ thống...</p>}{remoteContent.error && <p className="content-status content-status--error">{remoteContent.error}</p>}{filtered.length ? <div className="post-grid">{filtered.map((post) => <ContentCard key={post.id} post={post} onPlay={setVideo}/>)}</div> : <div className="empty-results">No community stories match that search. Try “protein” or “breakfast”.</div>}</section><EditorialGallery posts={blogItems}/><TopicAccordion/><VideoSection videos={videoItems} onPlay={setVideo}/><ReaderNotes/></main><Footer onAuth={setAuthMode}/><Chatbot/>{video && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Video preview"><div className="video-modal"><button className="modal-close" onClick={() => setVideo(null)} aria-label="Close video"><X/></button>{video.image ? <img src={video.image} alt=""/> : <div className="video-modal-placeholder"/>}<div className="modal-play"><Play fill="currentColor"/></div><div><span className="content-type">VIDEO PREVIEW</span><h2>{video.title}</h2><p>{video.description || 'Preview ready for guests. Create a free account for saved playlists and personalized picks.'}</p></div></div></div>}{authMode && <AuthModal mode={authMode} onClose={() => setAuthMode(null)} onSubmit={authenticate} onGoogle={() => window.location.assign(googleAuthUrl())}/>}</>;
}
