spring.application.name=swp391_group7_nutribot
server.port=${SERVER_PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=NutriBotV2;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
# JWT Configuration
jwt.secret=dXNlcl90b2tlbl9zZWNyZXRfa2V5X2Zvcl9udXRyaWJvdF9wcm9qZWN0X3N3cDM5MQ==
jwt.expiration=86400000
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
