spring.application.name=swp391_group7_nutribot

server.port=6969

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NutriBotV2;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false 

#Toàn bộ trang web phải nằm trong thư mục template
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JWT Configuration
jwt.secret=dXNlcl90b2tlbl9zZWNyZXRfa2V5X2Zvcl9udXRyaWJvdF9wcm9qZWN0X3N3cDM5MQ==
jwt.expiration=86400000
